name = "vinoflare"
compatibility_date = "2025-02-14"
main = "./src/index.tsx"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "vinoflare"
database_id = "8e27580b-773d-41d4-a134-1fc5b84d469a"
migrations_dir = "src/server/db/migrations"
