name = "vinoflare"
compatibility_date = "2025-02-14"
main = "./src/index.tsx"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "vinoflare"
database_id = "8e27580b-773d-41d4-a134-1fc5b84d469a"
migrations_dir = "drizzle/migrations"

[[kv_namespaces]]
binding = "KV"
id = "2feeb93090b342ec95a232fac333d8c7"

[[r2_buckets]]
binding = "IMG_BUCKET"
bucket_name = "vinoflare"

[[queues.producers]]
binding = "QUEUES"
queue = "vinoflare"

[[queues.consumers]]
queue = "vinoflare"
max_batch_size = 1
max_batch_timeout = 10
max_concurrency = 1
dead_letter_queue = "vinoflare-dlq"
