/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestAuthImport } from './routes/test-auth'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as QuotesIndexImport } from './routes/quotes.index'
import { Route as PostsIndexImport } from './routes/posts.index'
import { Route as QuotesIdImport } from './routes/quotes.$id'

// Create/Update Routes

const TestAuthRoute = TestAuthImport.update({
  id: '/test-auth',
  path: '/test-auth',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuotesIndexRoute = QuotesIndexImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const QuotesIdRoute = QuotesIdImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/test-auth': {
      id: '/test-auth'
      path: '/test-auth'
      fullPath: '/test-auth'
      preLoaderRoute: typeof TestAuthImport
      parentRoute: typeof rootRoute
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/test-auth': typeof TestAuthRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/posts': typeof PostsIndexRoute
  '/quotes': typeof QuotesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/test-auth': typeof TestAuthRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/posts': typeof PostsIndexRoute
  '/quotes': typeof QuotesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/test-auth': typeof TestAuthRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/posts/': typeof PostsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/test-auth'
    | '/quotes/$id'
    | '/posts'
    | '/quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/test-auth'
    | '/quotes/$id'
    | '/posts'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/test-auth'
    | '/quotes/$id'
    | '/posts/'
    | '/quotes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  TestAuthRoute: typeof TestAuthRoute
  QuotesIdRoute: typeof QuotesIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  TestAuthRoute: TestAuthRoute,
  QuotesIdRoute: QuotesIdRoute,
  PostsIndexRoute: PostsIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/profile",
        "/test-auth",
        "/quotes/$id",
        "/posts/",
        "/quotes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/test-auth": {
      "filePath": "test-auth.tsx"
    },
    "/quotes/$id": {
      "filePath": "quotes.$id.tsx"
    },
    "/posts/": {
      "filePath": "posts.index.tsx"
    },
    "/quotes/": {
      "filePath": "quotes.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
