/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as QuotesIndexImport } from './routes/quotes.index'
import { Route as QuotesIdImport } from './routes/quotes.$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QuotesIndexRoute = QuotesIndexImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRoute,
} as any)

const QuotesIdRoute = QuotesIdImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdImport
      parentRoute: typeof rootRoute
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes': typeof QuotesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes': typeof QuotesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/quotes/': typeof QuotesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quotes/$id' | '/quotes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quotes/$id' | '/quotes'
  id: '__root__' | '/' | '/quotes/$id' | '/quotes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuotesIdRoute: typeof QuotesIdRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuotesIdRoute: QuotesIdRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/quotes/$id",
        "/quotes/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/quotes/$id": {
      "filePath": "quotes.$id.tsx"
    },
    "/quotes/": {
      "filePath": "quotes.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
