import type { Ingredient } from "./types";

// 预定义的10种食材
export const PREDEFINED_INGREDIENTS: Ingredient[] = [
	{
		id: "tomato",
		name: "番茄",
		emoji: "🍅",
		processingTime: 6,
		failureRate: 0.1,
		description: "新鲜的红番茄，需要清洗和切块",
	},
	{
		id: "onion",
		name: "洋葱",
		emoji: "🧅",
		processingTime: 9,
		failureRate: 0.15,
		description: "辛辣的洋葱，需要剥皮和切丝",
	},
	{
		id: "carrot",
		name: "胡萝卜",
		emoji: "🥕",
		processingTime: 12,
		failureRate: 0.08,
		description: "橙色胡萝卜，需要削皮和切丁",
	},
	{
		id: "potato",
		name: "土豆",
		emoji: "🥔",
		processingTime: 15,
		failureRate: 0.12,
		description: "新鲜土豆，需要清洗、削皮和切块",
	},
	{
		id: "broccoli",
		name: "西兰花",
		emoji: "🥦",
		processingTime: 8,
		failureRate: 0.2,
		description: "绿色西兰花，需要分离花朵和清洗",
	},
	{
		id: "mushroom",
		name: "蘑菇",
		emoji: "🍄",
		processingTime: 6,
		failureRate: 0.18,
		description: "新鲜蘑菇，需要清洗和切片",
	},
	{
		id: "bell-pepper",
		name: "彩椒",
		emoji: "🫑",
		processingTime: 12,
		failureRate: 0.1,
		description: "彩色甜椒，需要去籽和切条",
	},
	{
		id: "garlic",
		name: "大蒜",
		emoji: "🧄",
		processingTime: 6,
		failureRate: 0.5,
		description: "香辣大蒜，需要剥皮和切碎",
	},
	{
		id: "cucumber",
		name: "黄瓜",
		emoji: "🥒",
		processingTime: 6,
		failureRate: 0.9,
		description: "新鲜黄瓜，需要清洗和切片",
	},
	{
		id: "eggplant",
		name: "茄子",
		emoji: "🍆",
		processingTime: 12,
		failureRate: 0.16,
		description: "紫色茄子，需要去蒂和切块",
	},
];
