name = "my-vino-api"
compatibility_date = "2025-06-17"
main = "./src/index.ts"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "vino-app-demo"
database_id = "7e9ac121-da74-40bd-a55a-0568de668797"
migrations_dir = "src/server/db/migrations"

